### ISSUE TITLE
new_from_db method does not work

### ISSUE THREAD

**Issue by mmacdonald1** [learn-co-curriculum/orm-mapping-db-to-ruby-object#10]
Cannot initialize the class with new without passing in arguments for instance variables. new_song.id won't exist if you do self.new.

**Comment by maxwellbenton** [comment]
Hi @mmacdonald1,

Thank you for providing this feedback. We've updated this lesson to provide some clarity around the use of `self.new` used in the example. In this particular case, since the example assumes there is an existing database of songs, those songs should all have IDs provided by the DB. Since there is no need to persist in this case, only to get the data and turn it into Ruby objects, `self.new` is used. This creates a temporary Ruby class instance of the song representing the stored data.

```ruby
def self.new_from_db(row)
  new_song = self.new  # self.new is the same as running Song.new
  new_song.id = row[0]
  new_song.name =  row[1]
  new_song.length = row[2]
  new_song  # return the newly created instance
end
```
